### ISSUE TITLE
question regarding PRINTBED120E15

### ISSUE THREAD

**Issue by daduke** [martinbudden/BabyCube#10]
in PRINTBED120E15, how is Printbed_Bracket_stl() fixed to the 1515 extrusions? The screws only extend from the bearings to the extrusions.

**Comment by engkon6** [comment]
Can try this design for inspiration.

![large_display_e6479228-2efd-41a4-8d66-d992db862059](https://github.com/user-attachments/assets/c6dc0bc6-215d-4977-8d54-4eb0d28bb3cd)

https://www.thingiverse.com/thing:5478574

**Comment by daduke** [comment]
thank you!
