### ISSUE TITLE
Error when opening Main.scad (LinuxMint 20.2 - OpenSCAD 2021.1)

### ISSUE THREAD

**Issue by andimoto** [martinbudden/BabyCube#2]
Hi,
this is a nice little printer. I'm thinking about to build one in a few months. Until then I want to get more details and maybe already buy some parts. 
I try to open the SCAD model. But unfortunately it does not work and I don't know if I open the correct file.

When I open "Main.scad" I get following error:
`
[WARNING: min() parameter could not be converted in file ../../../../.local/share/OpenSCAD/libraries/NopSCADlib/utils/core/rounded_rectangle.scad, line 25]
[WARNING: undefined operation (undefined / number) in file rounded_rectangle.scad, line 25]
[WARNING: undefined operation (number < undefined) in file rounded_rectangle.scad, line 25]
[ERROR: Assertion '(r < (min(size.x, size.y) / 2))' failed in file rounded_rectangle.scad, line 25](.local/share/OpenSCAD/libraries/NopSCADlib/utils/core/rounded_rectangle.scad)
`
Before this there are a few more Warnings and after this there is a trace back. 
I've installed NopSCADlib as described in the installation instructions. I've also tested NopSCADlib, which works fine.

Can you help me here? Is this some known issue or do I need to open something else?

System: Linux Mint 20.2
OpenSCAD 2021.1

Best regards
Andi

**Comment by andimoto** [comment]
Hi again,
I've opened Main.scad and got many errors.
Can you please tell me whats the target.scad File? I cannot find it in your Repository or in the NopSCADlib.

Best regards
Andi

**Comment by engkon6** [comment]
Hi Andi,
I also have the same error, you can try to follow below tutorial to import and edit the STL files in FreeCAD.
https://youtu.be/dr1qtaURrvI

I hope this can help.

**Comment by andimoto** [comment]
Hey,
thanks. I'm more interested  in exploring the model. Thats why I want to load it in OpenSCAD.
Usually I edit STL files in OpenSCAD.

**Comment by marbocub** [comment]
Hi, @andimoto

My `target.scad` is below.
~~~
include <config_BC200.scad>
$preview = true;
$target = "BC200";
~~~

**Comment by andimoto** [comment]
> 

Hey @marbocub ,
thanks.
If I understand this correctly I have to add a target.scad to the folder scad? Is that correct?
I still cannot get a render in OpenSCAD.

**Comment by marbocub** [comment]
Hi, @andimoto

Yes, the path is `scad/target.scad`.

**Comment by andimoto** [comment]
Sorry for late response. I was able to render the babycube model now. I still had some issues with case-sensitivity. I attach a patch with the files where the includes had case-sensitiv errors and OpenSCAD could not locate the files.

[babycube-patch.txt](https://github.com/martinbudden/BabyCube/files/10368153/babycube-patch.txt)
