### ISSUE TITLE
lowercase file name prevents building on case sensitive file systems

### ISSUE THREAD

**Issue by daduke** [martinbudden/BabyCube#6]
`include <coreXYReversed.scad>` needs to read `include <CoreXYReversed.scad>` in
https://github.com/martinbudden/BabyCube/blob/8fcd44794e0ac9d023c7a8b35ee7d3b93f0f9700/scad/utils/CoreXYBelts.scad#L3

**Comment by martinbudden** [comment]
Fixed in https://github.com/martinbudden/BabyCube/commit/f4ab3ad35dd0231cd2e7106868b4125804431c9b
