### ISSUE TITLE
BC220CF: part holes don't line up

### ISSUE THREAD

**Issue by daduke** [martinbudden/BabyCube#8]
`Y_Carriage_Brace_Right_RB` doesn't seem to fit `Y_Carriage_Right_RB` and same with `Y_Carriage_Brace_Left_RB` and `Y_Carriage_Left_RB`. In both cases 2 of the 3 holes line up, but the third is about 1 mm off.

**Comment by martinbudden** [comment]
I'll look into it.

**Comment by daduke** [comment]
great, thanks. Otherwise my build is almost finished (2 more CF walls missing), so I don't think there'll be more nasty surprises waiting

**Comment by martinbudden** [comment]
I've made a fix and uploaded the new STL files. You'll need to reprint both the Y_Carriage and the brace, since the holes have moved on both.

**Comment by daduke** [comment]
thanks! Printed my first Marvin today. But I need to do something about the bed, it's very wobbly. Checking your 1515 mod now...
![20241107_204401](https://github.com/user-attachments/assets/24093079-024b-4a0f-9318-e786037ba6ed)
